apiVersion: v1
kind: Service
metadata:
  name: OVERWRITE_PER_APP
spec:
  selector:
    sdr.appname: OVERWRITE_PER_APP
  type: ClusterIP
  ports:
  - name: OVERWRITE_PER_APP
    port: 8080
    protocol: TCP
    targetPort: 8080
