---

- name: Ambrosia External application deployment
  hosts: "{{ Environment }}_{{ app_name }}_{{grp}}"
  vars_files:
    - "../environments/{{pod}}/{{ Environment }}/hosts/group_vars/var.yml"

  become: true
  become_method: sudo
  become_user: "{{ ansible_become_user }}"
  vars:
    app_name: Ambrosia
    app_port: "{{ Ambrosiaexternal_port }}"
    app_version: "{{ AmbrosiaEx_version }}"
    expose_port: "{{ Ambrosiaexternal_env_port }}"
    expose_port1: "{{ Ambrosiaexternal_env_port1 }}"
    expose_port2: "{{ Ambrosiaexternal_env_port }}"
    ansible_become_user: "{{ ansible_become_user }}"

  environment:
    TEMP: "{{user_home}}/apps/tmp"

  tasks:
#     - include_role:
#         name: "../roles/shield_disable"
#       when:  (pod != 'QA' and traffic != 'netscalar')

#     - include_role:
#         name: "../roles/external_ui"
#       when:  pod != 'QA'

     - include_role:
         name: "../roles/ambrosiaex_appconfig"
       when:  pod != 'QA'


#     - include_role:
#         name: "../roles/shield_enable"
#       when:  (pod != 'QA' and traffic != 'netscalar')

  gather_facts: true
  post_tasks:
    - include_role:
        name: "../roles/post"
      when: pod == 'QA'
