---

- name: DeviceEsimConsumer application deployment
  hosts: "{{ Environment }}_{{ app_name }}_{{grp}}"
  vars_files:
    - "../environments/{{pod}}/{{ Environment }}/hosts/group_vars/var.yml"

  become: true
  become_method: sudo
  become_user: "{{ ansible_become_user }}"
  vars:
    app_name: device-esim-consumer
    app_port: "{{ DeviceEsimConsumer_port }}"
    expose_port: "{{ DeviceEsimConsumer_env_port }}"
    ansible_become_user: "{{ ansible_become_user }}"
    docker_user: "{{docker_user}}"
    healthcheck: "/health"

  environment:
    TEMP: "{{user_home}}/apps/tmp"

  tasks:
     #- include_role:
      #   name: "../roles/shield_disable"
       #when:  (pod != 'QA' and pod != 'esim-stg' and traffic != 'netscalar')
     - include_role:
        name: "../roles/device-esim-consumer"
       when: ( pod ==  'QA' or pod == 'stg' or pod == 'nc' or pod == 'rn')

     - include_role:
        name: "../roles/device-esim-consumer"
       when: ( pod ==  'QA_CHINA' or pod == 'stg_CHINA' or pod == 'nc_CHINA' or pod == 'rn_CHINA')

     #- include_role:
      #  name: "../roles/shield_enable"
       #when:  (pod != 'QA' and pod != 'esim-stg' and traffic != 'netscalar')

  gather_facts: true
  post_tasks:
    - include_role:
        name: "../roles/post"
      when: pod == 'QA'
