- name: Application Bounce
  hosts: "{{Environment}}"

  vars_files:
    - "../environments/{{pod}}/hosts/group_vars/var.yml"
  become: true
  become_method: sudo
  become_user: "{{ ansible_become_user }}"
  gather_facts: False
#  serial: "{{ serial_opts|default('1') }}"

  environment:
    TEMP: "{{user_home}}/apps/tmp"

  tasks:
     - include_role:
         name: "../roles/dr_app_manage"
