---

- name: ESCustomer application deployment
  hosts: "{{ Environment }}_{{ app_name }}_{{grp}}"
  vars_files:
    - "../environments/{{pod}}/{{ Environment }}/hosts/group_vars/var.yml"

  become: true
  become_method: sudo
  become_user: "{{ ansible_become_user }}"
  vars:
    app_name: ESCustomer
    app_port: "{{ ESCustomer_port }}"
    app_version: "{{ ESCustomer_version }}"
    expose_port: "{{ ESCustomer_env_port }}"
    expose_port2: "{{ ESCustomer_env_port2 }}"
    ansible_become_user: "{{ ansible_become_user }}"
    profile: "{{ ESCustomer_profile }}"
    token: "{{ token }}"
    vault_pass: "{{ vault_pass }}"
    docker_user: "{{docker_user}}"
    healthcheck: "customer/actuator/health"

  environment:
    TEMP: "{{user_home}}/apps/tmp"

  tasks:
     #- include_role:
      #   name: "../roles/shield_disable"
       #when:  (pod != 'QA' and pod != 'esim-stg' and traffic != 'netscalar')
     - include_role:
        name: "../roles/ESapps"
       when: ( pod ==  'QA' or pod == 'stg' or pod == 'nc' or pod == 'rn')

     - include_role:
        name: "../roles/ESChina"
       when: ( pod ==  'QA_CHINA' or pod == 'stg_CHINA' or pod == 'nc_CHINA' or pod == 'rn_CHINA')

     #- include_role:
      #  name: "../roles/shield_enable"
       #when:  (pod != 'QA' and pod != 'esim-stg' and traffic != 'netscalar')

  gather_facts: true
  post_tasks:
    - include_role:
        name: "../roles/post"
      when: pod == 'QA'
