---

- name: Hawkeye application deployment
  hosts: "{{ Environment }}_{{ app_name }}_{{grp}}"
  vars_files:
    - "../environments/{{pod}}/{{ Environment }}/hosts/group_vars/var.yml"

  become: true
  become_method: sudo
  become_user: "{{ ansible_become_user }}"
  vars:
    app_name: Hawkeye
    app_port: "{{ Hawkeye_port }}"
    app_version: "{{ Hawkeye_version }}"
    expose_port: "{{ Hawkeye_env_port }}"
    ansible_become_user: "{{ ansible_become_user }}"
    BDB_NAME: "Hawkeye-{{ansible_fqdn}}"

  environment:
    TEMP: "{{user_home}}/apps/tmp"

  tasks:
#     - include_role:
#         name: "../roles/shield_disable"
#       when:  (pod != 'QA' and traffic != 'netscalar')

     - include_role:
         name: "../roles/hawkeye_appconfig"

#     - include_role:
#         name: "../roles/shield_enable"
#       when:  (pod != 'QA' and traffic != 'netscalar')
  gather_facts: true
  post_tasks:
    - include_role:
        name: "../roles/post"
      when: pod == 'QA'
