---

- name: manufacturing-data-consumer application deployment
  hosts: "{{ Environment }}_{{ app_name }}_{{grp}}"
  vars_files:
    - "../environments/{{pod}}/{{ Environment }}/hosts/group_vars/var.yml"
  become: true
  become_method: sudo
  become_user: "{{ ansible_become_user }}"

  vars_prompt:

    - name: "action"
      prompt: "Please enter the command you wish to use against all apps (status, restart, stop or start)"
      default: "status"
      private: no

  vars:
    app_name: manufacturing-data-consumer
    app_port: "{{ manufacturing_data_consumer_port }}"
    app_version: "{{ manufacturing_data_consumer_version }}"
    expose_port: "{{ manufacturing_data_consumer_env_port }}"
    ansible_become_user: "{{ ansible_become_user }}"
    token: "{{ token }}"
    vault_pass: "{{ vault_pass }}"
    docker_user: "{{docker_user}}"
    healthcheck: "health"

  environment:
    TEMP: "{{user_home}}/apps/tmp"

  tasks:
  #   - include_role:
  #       name: "../roles/shield_disable"
  #     when:  (pod != 'QA' and traffic != 'netscalar')

     - include_role:
         name: "../roles/springboot"

  #   - include_role:
  #       name: "../roles/shield_enable"
  #     when:  (pod != 'QA' and traffic != 'netscalar')

  gather_facts: true
  post_tasks:
    - include_role:
        name: "../roles/post"
      when: pod == 'QA'
