---

- name: PhoenixPostProcess application deployment
  hosts: "{{ Environment }}_{{ app_name }}_{{grp}}"
  vars_files:
    - "../environments/{{pod}}/{{ Environment }}/hosts/group_vars/var.yml"

  become: true
  become_method: sudo
  become_user: "{{ ansible_become_user }}"
  vars:
    app_name: PhoenixPostProcess
    app_port: "{{ PhoenixPostProcess_port }}"
    app_version: "{{ PhoenixPostProcess_version }}"
    expose_port: "{{ PhoenixPostProcess_env_port }}"
    ansible_become_user: "{{ ansible_become_user }}"
    token: "{{ token }}"
    vault_pass: "{{ vault_pass }}"
    docker_user: "{{docker_user}}"
    BDB_NAME: "PhoenixPostProcess-{{ansible_fqdn}}"

  environment:
    TEMP: "{{user_home}}/apps/tmp"

  tasks:
   # - include_role:
   #    name: "../roles/rogue"
   #   when:  (pod != 'QA')

    - include_role:
        name: "../roles/phoenix_consumer_appconfig"
    #  when:  (pod == 'QA')

  gather_facts: true
  post_tasks:
    - include_role:
        name: "../roles/post"
      when: pod == 'QA'
