apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulset.yaml
#- service.yaml
#- networkpolicy.yaml
#- applenetworkpolicy.yaml
#- conduit-auth-secret.yaml
#- whisper-auth-secret.yaml
#- ingress.yaml
#- hpa.yaml